name: action
description: Perform action

runs:
  using: "composite"
  steps:
    - id: go
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "${#GITHUB_TOKEN}"
      shell: bash
