name: Add Project Items

on:
  workflow_dispatch:
    inputs:
      since:
        description: The date when the content was created
        required: true
        default: -7days

jobs:
  add:
    runs-on: ubuntu-latest
    name: Add project items
    strategy:
      matrix:
        # https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests
        query:
          - is:issue repo:protocol/.github
          - is:issue label:topic/devexp,topic/ci org:protocol org:ipfs org:ipfs-shipyard org:libp2p org:ipld org:multiformats org:filecoin-project org:filecoin-shipyard
          - is:issue mentions:galargh org:protocol org:ipfs org:ipfs-shipyard org:libp2p org:ipld org:multiformats org:filecoin-project org:filecoin-shipyard
          - is:pr is:open author:web3-bot
      fail-fast: false
    env:
      ORGANIZATION: protocol
      PROJECT: 14
      REPOSITORY: w3dt-stewards
      GITHUB_TOKEN: ${{ secrets.GALARGH_GITHUB_TOKEN }}
    steps:
      - id: query
        run: |
          echo "::set-output name=value::${{ matrix.query }} created:>=$(date --date='${{ github.event.inputs.since }}' +"%Y-%m-%d")"
        shell: bash
      - id: items
        uses: protocol/github-api-action-library/add-project-items-by-content-query@v1
        with:
          organization: ${{ env.ORGANIZATION }}
          project: ${{ env.PROJECT }}
          query: ${{ steps.query.outputs.value }}
      - id: content
        if: ${{ steps.items.outputs.failed-content-ids != '[]' }}
        run: |
          title='Add project items manually'
          body=$'```\n'"$(jq -r "[.[] | {\"\\(.id)\":.url}] | add | $(jq -r '[.[] | ".\"\(.)\""] | join(",")' <<< '${{ steps.items.outputs.failed-content-ids }}')" <<< '${{ steps.items.outputs.issues-or-pull-requests }}')"$'\n```'
          body="${body//$'\n'/\\\\n}"
          echo "::set-output name=value::[{\"title\":\"$title\",\"body\":\"$body\"}]"
        shell: bash
      - if: ${{ steps.items.outputs.failed-content-ids != '[]' }}
        uses: protocol/github-api-action-library/add-project-items-by-content@v1
        with:
          organization: ${{ env.ORGANIZATION }}
          project: ${{ env.PROJECT }}
          repository: ${{ env.REPOSITORY }}
          content: ${{ steps.content.outputs.value }}
