name: Playground
on:
  workflow_dispatch:
  pull_request_target:

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git config --global user.email '${{ github.actor }}@users.noreply.github.com>'
          git config --global user.name '${{ github.actor }}'
        shell: bash
      - env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "hello" > README.md
          git add --all
          git commit -m "test"
          git remote add ${{ github.event.pull_request.head.repo.full_name }} ${{ github.event.pull_request.head.repo.git_url }}
          git push ${{ github.event.pull_request.head.repo.full_name }} ${{ github.event.pull_request.head.ref }}

