name: Playground
on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          COMMENT="$(head -c 70000 < /dev/zero | tr '\0' '\141')"
          echo "${#COMMENT}"
        shell: bash
