name: Playground
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - run: |
          goarch="amd64-v1"
          IFS="-" read -ra arr <<< "$goarch"
          export GOARCH="${arr[0]}"
          export GOAMD64="${arr[1]}"
          echo $GOARCH
          echo $GOAMD64
        shell: bash
