name: Playground
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          chmod +x file.sh
          ./file.sh
