name: Playground
on:
  workflow_dispatch:
    inputs:
      test:
        description: test
        required: true
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    runs-on: ${{ fromJSON(vars['RUNNER_ubuntu'] || '"windows-latest"') }}
    steps:
      - run: |
          echo "value<<EOF" >> $GITHUB_OUTPUT
          echo "hello" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash
