name: Playground
on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: sudo touch /continue
      - uses: mxschmitt/action-tmate@v3
      - run: docker ps
      # - run: /tmp/tmate/tmate -S /tmp/tmate.sock show-messages

      
