name: Playground
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 120
        shell: bash
