name: Playground
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $TERM
          echo "$(tput sgr0)"
      - run: |
          echo $TERM
          echo "$(tput sgr0)"
        shell: bash
