name: Playground
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    runs-on: ${{ fromJSON(vars['RUNNER_ubuntu'] || '"windows-latest"') }}
    steps:
      - run: |
          echo "${{ toJSON(fromJSON(vars['RUNNER_ubuntu'] || '"windows-latest"')) }}"
        shell: bash
