name: Playground
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: galargh/.github/.github/actions/action@master
      - run: echo ${{ toJSON(env) }}
