name: Playground
on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: windows-latest
    steps:
      - name: Use msys2 on windows
        if: ${{ matrix.os == 'windows' }}
        shell: bash
        # The executable for msys2 is also called bash.cmd
        #   https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#shells
        # If we prepend its location to the PATH
        #   subsequent 'shell: bash' steps will use msys2 instead of gitbash
        run: echo "C:/msys64/usr/bin" >> $GITHUB_PATH
      - run: |
          pacman -S mingw-w64-x86_64-toolchain
          ls /c/msys64
          echo ""
          ls /c/msys64/mingw64
          echo ""
          ls /c/msys64/mingw64/bin
          echo ""
          find /c/msys64 -name pkg-config.exe
        shell: bash
