name: Playground
on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          head -c 16 < /dev/zero | tr '\0' '\141' >> COMMENT
          echo "${#COMMENT}"
        shell: bash
