name: Playground
on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: sudo touch /continue
      - uses: mxschmitt/action-tmate@v3
      - run: sleep 60
      - run: /tmp/tmate/tmate list-clients
      - run: /tmp/tmate/tmate show-messages

      
