name: Playground
on:
  workflow_dispatch:
  pull_request:
    paths: [ 'README.md' ]

jobs:
  playground:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: v2
      - uses: actions/checkout@v3
        with:
          path: v3
