name: Playground
on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          COMMENT="$(head -c 70000 < /dev/zero | tr '\0' '\141')"
          if [ ${#COMMENT} -ge 65000 ];
            echo "COMMENT=Terraform plans are too long to post as a comment. You can inspect them in full in [Plan > Comment > Show terraform plans](${github.server_url}/${github.repository}/actions/runs/${github.run_id}) instead." >> $GITHUB_ENV
          then
        shell: bash
