name: Playground
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    runs-on: ${{ vars['RUNNER_ubuntu'] || 'ubuntu-latest' }}
    steps:
      - run: |
          echo "hello"
        shell: bash
