name: Playground
on:
  workflow_dispatch:

jobs:
  playground1:
    runs-on: windows-latest
    steps:
      - run: |
          ls /c/msys64/mingw64/bin
        shell: bash
  playground2:
    runs-on: windows-2019
    steps:
      - run: |
          ls /c/msys64/mingw64/bin
        shell: bash
