name: Playground
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
    runs-on: ubuntu-latest
    steps:
      - uses: galargh/.github/.github/actions/action@master
      - run: echo ${{ toJSON(toJSON(env)) }}
      - run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
