name: Playground
on:
  workflow_dispatch:
    inputs:
      test:
        description: test
        default: latest
        required: true
  push:
    paths: [.github/workflows/playground.yml]

defaults:
  run:
    shell: bash

jobs:
  playground:
    runs-on: ${{ fromJSON(vars['RUNNER_ubuntu'] || '"windows-latest"') }}
    steps:
      - run: echo "EOF=$RANDOM" >> $GITHUB_ENV
      - run: echo "EOF=$EOF"
      - id: step
        run: |
          echo "value<<$EOF" >> $GITHUB_OUTPUT
          echo "hello" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
        shell: bash
      - run: echo "value=$VALUE"
        env:
          VALUE: ${{ steps.step.outputs.value }}
