name: Playground
on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: windows-latest
    steps:
      - run: |
          echo "1"
          ls /c/msys64/mingw64/bin
          echo "2"
          ls /c/msys64/mingw64
          echo "3"
          ls /c/msys64
        shell: bash
