name: Playground
on:
  workflow_dispatch:
    inputs:
      test:
        required: false
        description: Hello
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event.inputs) }}"
