name: Playground
on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup tmate session
        uses: pl-strflt/action-tmate@circleci
        if: runner.debug == '1'
        with:
          check-num-clients: true
          limit-access-to-actor: true
          wait: false
          wait-in-post: true
          wait-interval: '60000'
      - run: echo 'hello'


      
