name: Playground
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    runs-on: ${{ fromJSON(vars['RUNNER_ubuntu'] || '"???"') }}
    steps:
      - run: |
          echo "${{ toJSON(fromJSON(vars['RUNNER_ubuntu'] || '"???"')) }}"
        shell: bash
