name: Playground
on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ secrets.NPM_TOKEN }}" == "rubbish" ]]; then
            echo "bummer";
          elif [[ "${{ secrets.NPM_TOKEN }}" == "test" ]]; then
            echo "hooray";
          else
            echo "wtf";
          fi
        shell: bash
