name: Playground
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ vars['RUNNER_ubuntu'] || 'ubuntu-latest' }}"
        shell: bash
