name: Playground
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/playground.yml]

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - name: Find pull request number
        id: pull_request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUERY: repository:ipfs/github-mgmt 7f76bd2009912a9d0ff2ea475a7f007dafefefc0
        uses: actions/github-script@v6
        with:
          script: |
            const { data: result } = await github.rest.search.issuesAndPullRequests({
              q: process.env.QUERY,
              per_page: 1
            });
            return result;
      - run: echo ${{ fromJSON(steps.pull_request.outputs.result).total_count }}
