name: Playground
on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - if: true // runner.debug == '1'
        run: sudo touch /continue
      - if: true // runner.debug == '1'
        uses: mxschmitt/action-tmate@v3
      - if: true // runner.debug == '1'
        run: sleep 60
      - run: last

      
