name: Update Status History

on:
  workflow_dispatch:
  schedule:
    # “At minute 25 past every 8th hour.” - https://crontab.guru/#25_*/8_*_*_*
    - cron:  '25 */8 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - owner: pl-strflt
            project_number: 1
          # - owner: ipfs
          #   project_number: Kubo IPFS Stewards (PL EngRes)
          # - owner: libp2p
          #   project_number: Go libp2p Stewards (PL EngRes)
          # - owner: ipld
          #   project_number: "IPLD team's weekly tracker"
    env:
      GITHUB_TOKEN: ${{ secrets.GALARGH_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install && npm run build
        working-directory: scripts
      - run: |
          node lib/actions/update-status-history.js \
            --dryRun "false" \
            --org "${{ matrix.owner }}" \
            --projectNumber "${{ matrix.project_number }}"
        working-directory: scripts
