name: Update Badge

on:
  workflow_run:
    workflows: [Playground]
    types: [completed]

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(toJSON(github.event)) }}
        shell: bash
